# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Intro',
        ),
    ]
